version: '3.8'

services:
  backend:
    build:
      context: ./employee-management-backend
    ports:
      - "5000:5000"
    env_file:
      - ./employee-management-backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./employee-management-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./employee-management-frontend/.env
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
